name: khaber_app
description: A news and exploration app built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  dio: ^5.2.0

  shared_preferences: ^2.2.2
  http: ^1.1.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

